version: '3.7'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: jllllk/yamdb:latest
    restart: always
    volumes:
      - static_volume:/code/static
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - static_volume:/code/static
    ports:
      - 8000:80
    depends_on:
      - web