# Generated by Django 3.0.5 on 2020-07-30 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_auto_20200730_2101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
